### ISSUE TITLE
Update and delete modes are not working

### ISSUE THREAD

**Issue by srish** [DHTMLX/node-scheduler-demo#2]
I have been trying to integrate the scheduler with my node app. In the newly cloned repo, all the calendar modes: insert, update, and delete are working fine. But, when I try to add them to my project, without changing anything, the update and delete mode stop working. Do you have any thoughts on this?

**Comment by srish** [comment]
I think it's failing while sending data in dtmlXMLLoaderObject.prototype.loadXML function and resulting in an internal server error for the POST request domain_name/data?editing=true

**Comment by AlexKlimenkov** [comment]
I'm closing the issue due to long inactivity. 
If it's still actual - feel free to reopen and provide some additional details, i.e. what exactly happens when you try to update/delete, do you get an error message in the server response, do you have a node error on the server, and any other info that would help us to understand how the error occurs.
